# Generated by Django 5.2 on 2025-04-21 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='updated',
        ),
        migrations.AddField(
            model_name='otp',
            name='code',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_conf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
